import Foundation

/// Highly polished code generator parsing abstract visual tree nodes into production-ready, standard Swift source files.
public struct VisualUICodeGenerator {
    public init() {}

    /// Generates beautifully clean, standard, framework-specific code
    public func generateCode(for scene: VisualUIScene, targetFramework: VisualUIFramework) -> String {
        switch targetFramework {
        case .swiftUI:
            return generateSwiftUICode(scene: scene)
        case .appKit:
            return generateAppKitCode(scene: scene)
        case .uiKit:
            return generateUIKitCode(scene: scene)
        case .visionOS:
            return generateVisionOSCode(scene: scene)
        case .widgetKit:
            return generateWidgetKitCode(scene: scene)
        case .watchOS:
            return generateWatchOSCode(scene: scene)
        }
    }

    // MARK: - SwiftUI Code Generation

    private func generateSwiftUICode(scene: VisualUIScene) -> String {
        var output = """
//
//  VisualUIExportView.swift
//  Generated by SwiftCode Visual UI Builder
//  Production-Ready SwiftUI Code. No proprietary structures.
//

import SwiftUI
import Charts
import MapKit

struct VisualUIExportView: View {
"""
        // Append local state variables declared in scene properties
        let variablesString = scene.artboards.first?.rootNode.properties["declaredStateVariables"] ?? ""
        if !variablesString.isEmpty {
            let list = variablesString.components(separatedBy: ",")
            for variable in list {
                let parts = variable.components(separatedBy: " : ")
                let name = parts.first ?? ""
                let type = parts.last ?? "String"
                let initial = type == "Bool" ? "false" : (type == "Int" ? "0" : "\"\"")
                output += "\n    @State private var \(name): \(type) = \(initial)"
            }
        }

        output += """


    var body: some View {
"""
        if let artboard = scene.artboards.first {
            output += indentLines(generateNodeSwiftUI(node: artboard.rootNode), indentCount: 2)
        } else {
            output += "        Text(\"No Views Configured\")"
        }

        output += """

    }
}

#Preview {
    VisualUIExportView()
}
"""
        return output
    }

    private func generateNodeSwiftUI(node: VisualComponentNode) -> String {
        if node.isHidden { return "" }
        var str = ""

        switch node.type {
        case .vStack:
            let spacing = node.properties["spacing"] ?? "8"
            str = "VStack(spacing: \(spacing)) {\n"
            for child in node.children {
                str += indentLines(generateNodeSwiftUI(node: child), indentCount: 1) + "\n"
            }
            str += "}"

        case .hStack:
            let spacing = node.properties["spacing"] ?? "8"
            str = "HStack(spacing: \(spacing)) {\n"
            for child in node.children {
                str += indentLines(generateNodeSwiftUI(node: child), indentCount: 1) + "\n"
            }
            str += "}"

        case .zStack:
            str = "ZStack {\n"
            for child in node.children {
                str += indentLines(generateNodeSwiftUI(node: child), indentCount: 1) + "\n"
            }
            str += "}"

        case .group:
            str = "Group {\n"
            for child in node.children {
                str += indentLines(generateNodeSwiftUI(node: child), indentCount: 1) + "\n"
            }
            str += "}"

        case .groupBox:
            str = "GroupBox(\"\(node.name)\") {\n"
            for child in node.children {
                str += indentLines(generateNodeSwiftUI(node: child), indentCount: 1) + "\n"
            }
            str += "}"

        case .scrollView:
            str = "ScrollView {\n"
            for child in node.children {
                str += indentLines(generateNodeSwiftUI(node: child), indentCount: 1) + "\n"
            }
            str += "}"

        case .list:
            str = "List {\n"
            for child in node.children {
                str += indentLines(generateNodeSwiftUI(node: child), indentCount: 1) + "\n"
            }
            str += "}"

        case .form:
            str = "Form {\n"
            for child in node.children {
                str += indentLines(generateNodeSwiftUI(node: child), indentCount: 1) + "\n"
            }
            str += "}"

        case .text:
            let txt = node.properties["textValue"] ?? "Text Block"
            str = "Text(\"\(txt)\")"
            if let preset = node.properties["fontPreset"] {
                str += "\n    .font(.\(preset.lowercased().replacingOccurrences(of: " ", with: "")))"
            }

        case .button:
            let txt = node.properties["textValue"] ?? "Button"
            str = "Button(action: {\n    // Action response here\n}) {\n    Text(\"\(txt)\")\n}"

        case .label:
            let txt = node.properties["textValue"] ?? "Label"
            let sym = node.properties["sfSymbolName"] ?? "sparkles"
            str = "Label(\"\(txt)\", systemImage: \"\(sym)\")"

        case .image:
            str = "Image(systemName: \"photo\")"

        case .asyncImage:
            let url = node.properties["url"] ?? "https://example.com"
            str = "AsyncImage(url: URL(string: \"\(url)\"))"

        case .toggle:
            let txt = node.properties["textValue"] ?? "Toggle"
            str = "Toggle(\"\(txt)\", isOn: .constant(true))"

        case .picker:
            str = "Picker(\"Selection\", selection: .constant(1)) {\n    Text(\"Option 1\").tag(1)\n    Text(\"Option 2\").tag(2)\n}"

        case .slider:
            str = "Slider(value: .constant(0.5))"

        case .stepper:
            str = "Stepper(\"Stepper\", onIncrement: {}, onDecrement: {})"

        case .progressView:
            str = "ProgressView()"

        case .textField:
            str = "TextField(\"Input...\", text: .constant(\"\"))\n    .textFieldStyle(.roundedBorder)"

        case .secureField:
            str = "SecureField(\"Password...\", text: .constant(\"\"))\n    .textFieldStyle(.roundedBorder)"

        case .divider:
            str = "Divider()"

        case .spacer:
            str = "Spacer()"

        case .canvas:
            str = "Canvas { context, size in\n    let rect = CGRect(origin: .zero, size: size)\n    context.stroke(Path(rect), with: .color(.accentColor))\n}"

        case .charts:
            str = "Chart {\n    BarMark(x: .value(\"Label\", \"Category 1\"), y: .value(\"Value\", 5))\n    BarMark(x: .value(\"Label\", \"Category 2\"), y: .value(\"Value\", 12))\n}"

        case .map:
            str = "Map()"

        case .videoPlayer:
            str = "VideoPlayer(player: AVPlayer(url: URL(string: \"\")!))"

        case .webView:
            str = "WebViewRepresentable(url: URL(string: \"https://developer.apple.com\")!)"

        case .sfSymbol:
            let sym = node.properties["sfSymbolName"] ?? "sparkles"
            str = "Image(systemName: \"\(sym)\")"

        case .grid:
            str = "Grid {\n"
            for child in node.children {
                str += indentLines(generateNodeSwiftUI(node: child), indentCount: 1) + "\n"
            }
            str += "}"

        case .lazyVGrid:
            str = "LazyVGrid(columns: [GridItem(.flexible())]) {\n"
            for child in node.children {
                str += indentLines(generateNodeSwiftUI(node: child), indentCount: 1) + "\n"
            }
            str += "}"

        case .lazyHGrid:
            str = "LazyHGrid(rows: [GridItem(.flexible())]) {\n"
            for child in node.children {
                str += indentLines(generateNodeSwiftUI(node: child), indentCount: 1) + "\n"
            }
            str += "}"

        case .navigationStack:
            str = "NavigationStack {\n"
            for child in node.children {
                str += indentLines(generateNodeSwiftUI(node: child), indentCount: 1) + "\n"
            }
            str += "}"

        case .navigationSplitView:
            str = "NavigationSplitView {\n"
            if node.children.count >= 1 {
                str += "    // Sidebar\n"
                str += indentLines(generateNodeSwiftUI(node: node.children[0]), indentCount: 1) + "\n"
            } else {
                str += "    Text(\"Sidebar\")\n"
            }
            str += "} detail: {\n"
            if node.children.count >= 2 {
                str += indentLines(generateNodeSwiftUI(node: node.children[1]), indentCount: 1) + "\n"
            } else {
                str += "    Text(\"Detail View\")\n"
            }
            str += "}"

        case .tabView:
            str = "TabView {\n"
            for child in node.children {
                str += indentLines(generateNodeSwiftUI(node: child), indentCount: 1) + "\n"
                str += "    .tabItem {\n"
                str += "        Label(\"\(child.name)\", systemImage: \"star\")\n"
                str += "    }\n"
            }
            str += "}"
        }

        // Apply universal styling modifiers
        if let padding = node.properties["padding"], Double(padding) ?? 0 > 0 {
            str += "\n.padding(\(padding))"
        }
        if let foreColor = node.properties["foregroundColor"] {
            str += "\n.foregroundColor(Color(hex: \"\(foreColor)\"))"
        }
        if let backColor = node.properties["backgroundColor"] {
            str += "\n.background(Color(hex: \"\(backColor)\"))"
        }
        if let width = node.properties["width"], !width.isEmpty {
            str += "\n.frame(width: \(width))"
        }
        if let height = node.properties["height"], !height.isEmpty {
            str += "\n.frame(height: \(height))"
        }
        if let radius = node.properties["cornerRadius"], Double(radius) ?? 0 > 0 {
            str += "\n.cornerRadius(\(radius))"
        }

        return str
    }

    // MARK: - AppKit Code Generation

    private func generateAppKitCode(scene: VisualUIScene) -> String {
        return """
//
//  VisualUIExportView.swift
//  Generated by SwiftCode Visual UI Builder
//  AppKit Native Code for macOS Desktop.
//

import AppKit

class VisualUIExportViewController: NSViewController {
    override func loadView() {
        let mainView = NSView(frame: NSRect(x: 0, y: 0, width: 800, height: 600))
        mainView.wantsLayer = true
        mainView.layer?.backgroundColor = NSColor.windowBackgroundColor.cgColor

        let stackView = NSStackView()
        stackView.orientation = .vertical
        stackView.alignment = .centerX
        stackView.spacing = 12
        stackView.translatesAutoresizingMaskIntoConstraints = false
        mainView.addSubview(stackView)

        NSLayoutConstraint.activate([
            stackView.centerXAnchor.constraint(equalTo: mainView.centerXAnchor),
            stackView.centerYAnchor.constraint(equalTo: mainView.centerYAnchor)
        ])

        let label = NSTextField(labelWithString: "Native AppKit Content")
        label.font = NSFont.boldSystemFont(ofSize: 18)
        stackView.addArrangedSubview(label)

        self.view = mainView
    }
}
"""
    }

    // MARK: - UIKit Code Generation

    private func generateUIKitCode(scene: VisualUIScene) -> String {
        return """
//
//  VisualUIExportView.swift
//  Generated by SwiftCode Visual UI Builder
//  UIKit Native Code.
//

import UIKit

class VisualUIExportViewController: UIViewController {
    override func viewDidLoad() {
        super.viewDidLoad()
        view.backgroundColor = .systemBackground

        let stackView = UIStackView()
        stackView.axis = .vertical
        stackView.alignment = .center
        stackView.spacing = 16
        stackView.translatesAutoresizingMaskIntoConstraints = false
        view.addSubview(stackView)

        NSLayoutConstraint.activate([
            stackView.centerXAnchor.constraint(equalTo: view.centerXAnchor),
            stackView.centerYAnchor.constraint(equalTo: view.centerYAnchor)
        ])

        let titleLabel = UILabel()
        titleLabel.text = "Native UIKit Layout"
        titleLabel.font = UIFont.boldSystemFont(ofSize: 22)
        stackView.addArrangedSubview(titleLabel)
    }
}
"""
    }

    // MARK: - visionOS Code Generation

    private func generateVisionOSCode(scene: VisualUIScene) -> String {
        return """
//
//  VisualUIExportView.swift
//  Generated by SwiftCode Visual UI Builder
//  visionOS Spatial UI.
//

import SwiftUI
import RealityKit

struct VisualUIExportView: View {
    var body: some View {
        VStack(spacing: 24) {
            Text("Spatial visionOS Workspace")
                .font(.largeTitle)
                .glassBackgroundEffect()

            RealityView { content in
                // Add spatial RealityKit model nodes here
            }
            .frame(width: 300, height: 300)
        }
    }
}
"""
    }

    // MARK: - WidgetKit Code Generation

    private func generateWidgetKitCode(scene: VisualUIScene) -> String {
        return """
//
//  VisualUIExportView.swift
//  Generated by SwiftCode WidgetKit Template
//

import WidgetKit
import SwiftUI

struct Provider: TimelineProvider {
    func placeholder(in context: Context) -> SimpleEntry {
        SimpleEntry(date: Date())
    }

    func getSnapshot(in context: Context, completion: @escaping (SimpleEntry) -> ()) {
        let entry = SimpleEntry(date: Date())
        completion(entry)
    }

    func getTimeline(in context: Context, completion: @escaping (Timeline<Entry>) -> ()) {
        let entries = [SimpleEntry(date: Date())]
        let timeline = Timeline(entries: entries, policy: .atEnd)
        completion(timeline)
    }
}

struct SimpleEntry: TimelineEntry {
    let date: Date
}

struct WidgetEntryView: View {
    var entry: Provider.Entry

    var body: some View {
        VStack {
            Text("Widget Workspace")
                .font(.headline)
            Text(entry.date, style: .time)
                .font(.caption)
        }
    }
}
"""
    }

    // MARK: - watchOS Code Generation

    private func generateWatchOSCode(scene: VisualUIScene) -> String {
        return """
//
//  VisualUIExportView.swift
//  Generated by SwiftCode WatchOS Template
//

import SwiftUI

struct WatchUIExportView: View {
    var body: some View {
        ScrollView {
            VStack(spacing: 12) {
                Image(systemName: "applewatch")
                    .font(.title)
                    .foregroundColor(.green)
                Text("watchOS Workspace")
                    .font(.headline)
            }
        }
    }
}
"""
    }

    // MARK: - Formatting Helpers

    private func indentLines(_ source: String, indentCount: Int) -> String {
        let indent = String(repeating: "    ", count: indentCount)
        let lines = source.components(separatedBy: "\n")
        return lines.map { $0.isEmpty ? "" : indent + $0 }.joined(separator: "\n")
    }
}
