import Foundation

/// [CRITICAL SYSTEM FILE] - HIGH RISK
/// The primary execution bridge for file and project operations. Ensures all changes are real and integrated.
public final class _AssistCriticalExecutionEngine {
    private let context: AssistContext
    private let baseEngine: AssistExecutionEngine

    public init(context: AssistContext) {
        self.context = context
        self.baseEngine = AssistExecutionEngine(context: context, registry: AssistToolRegistry())
    }

    /// Executes a plan and ensures all new files are visible to the project.
    @MainActor
    public func execute(plan: inout AssistExecutionPlan) async throws {
        await context.logger.info("Executing via Critical Execution Engine", toolId: "CriticalExecution")

        for i in 0..<plan.steps.count {
            let step = plan.steps[i]
            if step.toolId == "file_write" || step.toolId == "createFile" {
                if let path = step.input["path"] {
                    if !context.fileSystem.exists(at: path) {
                        try await createMissingFile(path: path)
                    }
                }
            }
        }

        try await baseEngine.execute(plan: &plan)

        // After execution, force a refresh of the project state to ensure UI and file system are in sync.
        if let project = ProjectManager.shared.activeProject {
            ProjectManager.shared.refreshFileTree(for: project)
        }
    }

    public func createMissingFile(path: String) async throws {
        await context.logger.info("Automatically creating missing file: \(path)", toolId: "CriticalExecution")

        let fileExtension = (path as NSString).pathExtension.lowercased()
        let content: String

        switch fileExtension {
        case "swift":
            content = """
import SwiftUI

struct \( (path as NSString).lastPathComponent.replacingOccurrences(of: ".swift", with: "") ): View {
    var body: some View {
        Text("Generated by Assist")
    }
}
"""
        case "md":
            content = "# \( (path as NSString).lastPathComponent )\n\nGenerated by Assist\n"
        case "json":
            content = "{}"
        default:
            content = "// Generated by Assist\n"
        }

        try context.fileSystem.writeFile(at: path, content: content)

        // Register in Xcode project
        await registerInXcode(path: path)
    }

    private func registerInXcode(path: String) async {
        // IDs for registration must be 24-character hex strings
        let fileId = generateRandomHexID()
        let buildFileId = generateRandomHexID()
        let fileName = (path as NSString).lastPathComponent

        let pbxPath = "SwiftCode.xcodeproj/project.pbxproj"

        // 1. Add to PBXFileReference
        let fileRefEntry = "\t\t\(fileId) /* \(fileName) */ = {isa = PBXFileReference; lastKnownFileType = sourcecode.swift; path = \"\(path)\"; sourceTree = \"<group>\"; };"
        // macOS sed -i '' compatibility
        let addFileRefCmd = "sed -i '' '/\\/* Begin PBXFileReference section *\\//a\\\\\\n\(fileRefEntry)' \(pbxPath)"

        // 2. Add to PBXBuildFile
        let buildFileEntry = "\t\t\(buildFileId) /* \(fileName) in Sources */ = {isa = PBXBuildFile; fileRef = \(fileId) /* \(fileName) */; };"
        let addBuildFileCmd = "sed -i '' '/\\/* Begin PBXBuildFile section *\\//a\\\\\\n\(buildFileEntry)' \(pbxPath)"

        // 3. Add to Assist Group (ASBG0000000000000000001)
        let addGroupChildCmd = "sed -i '' '/ASBG0000000000000000001 \\/* Assist *\\/ = {/,/};/ s/children = (/children = (\\\\\\n\\\\t\\\\t\\\\t\\\\t\(fileId) \\/* \(fileName) *\\\\/,/' \(pbxPath)"

        // 4. Add to Sources Build Phase (AA000001000000000000000B_SRC)
        let addBuildPhaseCmd = "sed -i '' '/AA000001000000000000000B_SRC \\/* Sources *\\/ = {/,/};/ s/files = (/files = (\\\\\\n\\\\t\\\\t\\\\t\\\\t\(buildFileId) \\/* \(fileName) in Sources *\\\\/,/' \(pbxPath)"

        let fullCmd = "\(addFileRefCmd) && \(addBuildFileCmd) && \(addGroupChildCmd) && \(addBuildPhaseCmd)"

        #if os(macOS)
        let process = Process()
        process.executableURL = URL(fileURLWithPath: "/bin/bash")
        process.arguments = ["-c", fullCmd]
        do {
            try process.run()
            process.waitUntilExit()
            if process.terminationStatus == 0 {
                await context.logger.info("Registered \(fileName) in Xcode project with ID \(fileId)", toolId: "CriticalExecution")
            } else {
                await context.logger.error("Failed to register \(fileName) in Xcode project (exit code: \(process.terminationStatus))", toolId: "CriticalExecution")
            }
        } catch {
            await context.logger.error("Failed to execute Xcode registration for \(fileName): \(error.localizedDescription)", toolId: "CriticalExecution")
        }
        #else
        await context.logger.warning("Skipping Xcode registration for \(fileName): Process is only supported on macOS.", toolId: "CriticalExecution")
        #endif
    }

    private func generateRandomHexID() -> String {
        let chars = Array("0123456789ABCDEF")
        return String((0..<24).compactMap { _ in chars.randomElement() })
    }
}
