import Foundation

public struct AssistGenerateFileTool: AssistTool {
    public let id = "code_generate"
    public let name = "Generate File"
    public let description = "Generates a new file with boilerplate or specific logic."

    public init() {}

    public func execute(input: [String: Any], context: AssistContext) async throws -> AssistToolResult {
        guard let path = input["path"] as? String else {
            return .failure("Missing required parameter: path")
        }
        guard let template = input["template"] as? String else {
            return .failure("Missing required parameter: template")
        }

        if context.fileSystem.exists(at: path) {
            return .failure("Target file already exists: \(path)")
        }

        let fileName = URL(fileURLWithPath: path).deletingPathExtension().lastPathComponent
        let rendered = renderTemplate(template: template, fileName: fileName, input: input)

        do {
            try context.fileSystem.writeFile(at: path, content: rendered)
            return .success("Generated file \(path) using template '\(template)'", data: ["path": path])
        } catch {
            return .failure("Failed generating file \(path): \(error.localizedDescription)")
        }
    }

    private func renderTemplate(template: String, fileName: String, input: [String: Any]) -> String {
        let moduleName = (input["module"] as? String) ?? "SwiftCode"
        switch template.lowercased() {
        case "swift_struct":
            return "import Foundation\n\npublic struct \(fileName) {\n    public init() {}\n}\n"
        case "swift_class":
            return "import Foundation\n\npublic final class \(fileName) {\n    public init() {}\n}\n"
        case "swiftui_view":
            return "import SwiftUI\n\nstruct \(fileName): View {\n    var body: some View {\n        Text(\"\(fileName)\")\n    }\n}\n\n#Preview {\n    \(fileName)()\n}\n"
        case "test":
            return "import XCTest\n@testable import \(moduleName)\n\nfinal class \(fileName): XCTestCase {\n    func testExample() {\n        XCTAssertTrue(true)\n    }\n}\n"
        default:
            return "// Generated by AssistGenerateFileTool\n"
        }
    }
}
