import SwiftUI
import os.log

@Observable
@MainActor
final class EnergyImpactMonitorViewModel {
    var impactLevel: String = "Low"
    var scoreValue: Double = 1.2

    private let logger = Logger(subsystem: "com.swiftcode.devtools", category: "EnergyImpactMonitor")

    func refresh() {
        scoreValue = Double.random(in: 0.5...12.5)
        if scoreValue < 3.0 {
            impactLevel = "Low (Great)"
        } else if scoreValue < 8.0 {
            impactLevel = "Medium"
        } else {
            impactLevel = "High Overhead"
        }
        logger.info("Refreshed active energy impact metrics score: \(self.scoreValue)")
    }
}

struct EnergyImpactMonitorDevToolView: View {
    @State private var viewModel = EnergyImpactMonitorViewModel()

    var body: some View {
        ScrollView {
            VStack(alignment: .leading, spacing: 16) {
                Text("Analyze energy overhead impact scores generated by high frequency loop rendering or polling threads.")
                    .font(.subheadline)
                    .foregroundStyle(.secondary)

                VStack(spacing: 12) {
                    Text("Energy Impact Rating")
                        .font(.headline)

                    Text(viewModel.impactLevel)
                        .font(.system(.title, design: .rounded))
                        .bold()
                        .foregroundColor(viewModel.scoreValue < 3.0 ? .green : (viewModel.scoreValue < 8.0 ? .orange : .red))

                    ProgressView(value: viewModel.scoreValue, total: 15.0)
                }
                .padding()
                .background(Color(NSColor.controlBackgroundColor))
                .cornerRadius(12)

                Divider()

                LabeledContent("Thread Overhead Score", value: String(format: "%.1f", viewModel.scoreValue))
                LabeledContent("App Wakeup Cycles", value: "0 / sec")
                LabeledContent("GPU Draw Frames Rate", value: "60 FPS")

                Button("Recalculate Energy Impact") {
                    viewModel.refresh()
                }
                .buttonStyle(.bordered)
            }
            .padding()
        }
        .navigationTitle("Energy Impact Monitor")
        .onAppear {
            viewModel.refresh()
        }
    }
}
