import SwiftUI

struct JSONToGoView: View {
    @State private var jsonInput = ""
    @State private var output = ""
    @State private var structName = "AutoGenerated"

    var body: some View {
        VStack(spacing: 0) {
            HStack {
                Text("Struct Name:")
                TextField("AutoGenerated", text: $structName)
                    .textFieldStyle(.roundedBorder)
                    .frame(width: 200)
                Spacer()
                Button("Generate Go") { generate() }
                    .buttonStyle(.borderedProminent)
            }
            .padding()

            HSplitView {
                TextEditor(text: $jsonInput)
                    .font(.system(.body, design: .monospaced))
                TextEditor(text: .constant(output))
                    .font(.system(.body, design: .monospaced))
            }
        }
        .navigationTitle("JSON to Go")
    }

    func generate() {
        guard let data = jsonInput.data(using: .utf8),
              let json = try? JSONSerialization.jsonObject(with: data) as? [String: Any] else {
            output = "Invalid JSON"
            return
        }
        output = "type \(structName) struct {\n"
        for (key, value) in json {
            let type = getGoType(value)
            let fieldName = key.capitalized
            output += "    \(fieldName) \(type) `json:\"\(key)\"`\n"
        }
        output += "}"
    }

    func getGoType(_ value: Any) -> String {
        if value is String { return "string" }
        if value is Int { return "int" }
        if value is Double { return "float64" }
        if value is Bool { return "bool" }
        return "interface{}"
    }
}
